name: conifer
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    run_as_root:
      # Temporary hack to get a Debian package to install
      # https://github.com/lando/lando/issues/1554
      - echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf
      - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
      - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list

      - apt-get update
      - apt-get install zip

    run:
      - composer install
      - /app/scripts/setup-wordpress.sh

    overrides:
      environment:
        # Pass any non-empty CI envvar from the host into Lando
        # This is so we can force non-interactive mode setting up WP
        CI: ${CI:-''}

  database:
    type: mysql:5.7

  gitbook:
    type: node:10

    run:
      - yarn
      - /app/scripts/build-docs.sh

  cypress:
    type: node:10

    run:
      - yarn cypress install

    overrides:
      image: 'sitecrafting/lando-cypress-wordpress:latest'

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

  docs:
    type: nginx:1.14
    ssl: true
    webroot: docs/_book

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.sh'
    description: 'Install and configure WordPress for custom plugin dev'

  install-test-themes:
    service: appserver
    cmd: 'rsync --verbose --archive --recursive /app/test/themes/ /app/wp/wp-content/themes/'
    description: 'Sync test themes for e2e testing'

  debug:
    service: appserver
    cmd: 'tail -f /app/wp/wp-content/debug.log'
    description: 'Get real-time WP debug log output'

  cypress:
    service: cypress
    cmd: 'yarn cypress'
    description: 'Run arbitrary cypress commands'

  e2e:
    service: cypress
    cmd: 'yarn cypress run'
    description: 'Run end-to-end tests'

  unit:
    service: appserver
    cmd: '/app/vendor/bin/phpunit'
    description: 'Run unit tests'

  sniff:
    service: appserver
    cmd: 'composer sniff'
    description: 'Run phpcs code sniffer'

  sniff-summary:
    service: appserver
    cmd: 'composer sniff-summary'
    description: 'Summarize phpcs results'

  sniff-fix:
    service: appserver
    cmd: 'composer sniff-fix'
    description: 'Fix coding standards issues that are automatically fixable'

  release:
    service: appserver
    cmd: '/app/scripts/build-release.sh'
    description: 'Build a downloadable release of the Conifer WordPress plugin'

  docs:
    service: gitbook
    cmd: '/app/scripts/build-docs.sh /app/docs'
    description: 'Build documentation in _book folder using Gitbook'

  gitbook:
    service: gitbook
    cmd: 'yarn gitbook'
    description: 'Run arbitrary gitbook commands'

events:
  pre-docs:
    - appserver: '/app/scripts/build-api-md.sh'

  pre-e2e:
    - appserver: 'echo installing test themes...'
    - appserver: 'rsync --verbose --archive --recursive /app/test/themes/ /app/wp/wp-content/themes/'

proxy:
  appserver:
    - conifer.lndo.site

  mailhog:
    - mail.conifer.lndo.site

  phpmyadmin:
    - phpmyadmin.conifer.lndo.site

  docs:
    - docs.conifer.lndo.site
