name: conifer
recipe: wordpress
config:
  webroot: wp
  php: '7.0'

services:
  appserver:
    run_as_root:
      - apt-get update
      - apt-get install zip

    run:
      - cd $LANDO_MOUNT && composer install
      - cd $LANDO_MOUNT && scripts/setup-wordpress.sh

    overrides:
      services:
        environment:
          # Pass any non-empty CI envvar from the host into Lando
          # This is so we can force non-interactive mode setting up WP
          CI: ${CI:-''}

  database:
    type: mysql:5.7

  node:
    type: node:6.11

    globals:
      yarn: "1.6.0"

    run:
      - cd $LANDO_MOUNT && yarn
      - cd $LANDO_MOUNT && yarn cypress install
      - $LANDO_MOUNT/scripts/build-docs.sh

    overrides:
      services:
        image: 'sitecrafting/lando-node-cypress:latest'

  phpmyadmin:
    type: phpmyadmin:4.7

  mailhog:
    type: mailhog:v1.0.0
    hogfrom:
      - appserver

  docs:
    type: nginx:1.13
    ssl: true
    webroot: docs/_book

tooling:
  install:
    service: appserver
    cmd: '/app/scripts/setup-wordpress.sh'
    description: 'Install and configure WordPress for custom plugin dev'

  install-test-themes:
    service: appserver
    cmd: 'rsync --verbose --archive --recursive /app/test/themes/ /app/wp/wp-content/themes/'
    description: 'Sync test themes for e2e testing'

  yarn:
    service: node

  debug:
    service: appserver
    cmd: 'tail -f /app/wp/wp-content/debug.log'
    description: 'Get real-time WP debug log output'

  cypress:
    service: node
    cmd: 'yarn cypress'
    description: 'Run arbitrary cypress commands'

  e2e:
    service: node
    cmd: 'yarn cypress run'
    description: 'Run end-to-end tests'

  unit:
    service: appserver
    cmd: 'vendor/bin/phpunit'
    description: 'Run unit tests'

  sniff:
    service: appserver
    cmd: 'composer sniff'
    description: 'Run phpcs code sniffer'

  sniff-summary:
    service: appserver
    cmd: 'composer sniff-summary'
    description: 'Summarize phpcs results'

  sniff-fix:
    service: appserver
    cmd: 'composer sniff-fix'
    description: 'Fix coding standards issues that are automatically fixable'

  release:
    service: appserver
    cmd: '/app/scripts/build-release.sh'
    description: 'Build a downloadable release of the Conifer WordPress plugin'

  docs:
    service: node
    cmd: '/app/scripts/build-docs.sh /app/docs'
    description: 'Build documentation in _book folder using Gitbook'

  gitbook:
    service: node
    cmd: 'yarn gitbook'
    description: 'Run arbitrary gitbook commands'

events:
  pre-docs:
    - appserver: 'cd $LANDO_MOUNT && ./scripts/build-api-md.sh'
  pre-e2e:
    # TODO don't destroy dev database state every time?
    - appserver: '
      cd $LANDO_MOUNT &&
      wp fixture install test/fixtures/meta-search.yaml --yes
      '

proxy:
  appserver:
    - conifer.lndo.site

  mailhog:
    - mail.conifer.lndo.site

  phpmyadmin:
    - phpmyadmin.conifer.lndo.site

  docs:
    - docs.conifer.lndo.site
